# Generated by Django 3.1.1 on 2020-11-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_des', models.TextField(null=True)),
                ('long_des', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
